from pydantic import BaseModel, ConfigDict
from typing import Optional

class TaskBase(BaseModel):
    """
    Base Pydantic model for common task attributes.
    """
    title: str
    description: Optional[str] = None
    completed: bool = False

class TaskCreate(TaskBase):
    """
    Pydantic model for creating a new task.
    Inherits from TaskBase.
    """
    pass

class TaskUpdate(BaseModel):
    """
    Pydantic model for updating an existing task.
    All fields are optional to allow partial updates.
    """
    title: Optional[str] = None
    description: Optional[str] = None
    completed: Optional[bool] = None

class TaskResponse(TaskBase):
    """
    Pydantic model for a task response.
    Includes the 'id' field which is generated by the database.
    """
    id: int

    model_config = ConfigDict(from_attributes=True) # Allow ORM models to be converted
